version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3307:3306
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: gift_certificates
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
        test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
  tomcat:
    container_name: tomcat
    restart: unless-stopped
    image: tomcat:9
    volumes:
      - "./gift-app.war:/usr/local/tomcat/webapps/gift-app.war"
      - "./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml"
    ports:
      - 8082:8080
    depends_on:
      mysql:
          condition: service_healthy
   